mediators:
    - MonteCarlo

simulation:
  nsim: 1000000
  builder_choice: 1

 pricers:
    - EuropeanPricer
    - AsianPricer
    - BarrierPricer

options:
    - Strike: 65
      Expiration: 0.25
      volatility: 0.30
      Dividend: 0.0
      OptionType: 1
      InterestRate: 0.08
      Beta: 1.0
      InitialPrice: 60
    - Strike: 65
      Expiration: 0.25
      Volatility: 0.30
      Dividend: 0.0
      OptionType: -1
      InterestRate: 0.08
      Beta: 1.0
      InitialPrice: 60
          
